-- 进件管理表
CREATE TABLE finance_application (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  customer_name VARCHAR(100) NOT NULL COMMENT '客户姓名',
  city VARCHAR(50) COMMENT '城市',
  channel VARCHAR(50) COMMENT '渠道',
  sign_date DATE COMMENT '签约日期',
  salesperson VARCHAR(50) COMMENT '业务员',
  repayment_date DATE COMMENT '还款日期',
  notarization VARCHAR(10) COMMENT '公证',
  contract_amount DECIMAL(15,2) COMMENT '签约金额',
  contract_rate VARCHAR(20) COMMENT '合同点位',
  receivable_amount DECIMAL(15,2) COMMENT '应收金额',
  buyout_amount DECIMAL(15,2) COMMENT '买断金额',
  deposit DECIMAL(15,2) COMMENT '保证金',
  release_amount DECIMAL(15,2) COMMENT '放款金额',
  rebate_rate VARCHAR(20) COMMENT '返点比例',
  rebate_amount DECIMAL(15,2) COMMENT '返点金额',
  commission_rate VARCHAR(20) COMMENT '佣金比例',
  commission_fee DECIMAL(15,2) COMMENT '佣金费用',
  risk_control_person VARCHAR(50) COMMENT '风控人员',
  debt_settlement_amount DECIMAL(15,2) COMMENT '债务结清金额',
  department VARCHAR(100) COMMENT '部门',
  household VARCHAR(100) COMMENT '户籍',
  education VARCHAR(20) COMMENT '学历',
  company_full_name VARCHAR(200) COMMENT '公司全称',
  company_type VARCHAR(50) COMMENT '公司性质',
  housing_fund_base DECIMAL(15,2) COMMENT '公积金基数',
  salary DECIMAL(15,2) COMMENT '工资',
  operation_date DATE COMMENT '操作日期',
  remark TEXT COMMENT '备注',
  is_del int DEFAULT 0 COMMENT '是否删除',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_customer_name (customer_name),
  INDEX idx_city (city),
  INDEX idx_channel (channel),
  INDEX idx_sign_date (sign_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='进件信息表';

-- 出款管理表
CREATE TABLE finance_disbursement (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  application_id BIGINT NOT NULL COMMENT '进件ID',
  customer_name VARCHAR(100) NOT NULL COMMENT '客户姓名',
  channel VARCHAR(50) NOT NULL COMMENT '渠道',
  city VARCHAR(50) NOT NULL COMMENT '城市',
  sign_date DATE NOT NULL COMMENT '签约日期',
  disbursement_amount DECIMAL(15,2) NOT NULL COMMENT '出款金额',
  disbursement_type VARCHAR(50) NOT NULL COMMENT '出款类型',
  period int NOT NULL COMMENT '期数',
  disbursement_date DATE COMMENT '出款日期',
  account VARCHAR(50) NOT NULL COMMENT '出款账户',
  interest_rate DECIMAL(5,2) NOT NULL COMMENT '出款利率',
  monthly_repayment_amount DECIMAL(15,2) NOT NULL COMMENT '月还款金额',
  channel_point VARCHAR(50) COMMENT '通道点位',
  channel_fee VARCHAR(50) COMMENT '通道费用',
  salesperson VARCHAR(50) COMMENT '业务员',
  remark TEXT COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_customer_name (customer_name),
  INDEX idx_disbursement_date (disbursement_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出款管理表';

-- 回款管理表
CREATE TABLE finance_payment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  application_id BIGINT NOT NULL COMMENT '进件ID',
  customer_name VARCHAR(100) NOT NULL COMMENT '客户姓名',
  channel  VARCHAR(50) NOT NULL COMMENT '渠道',
  city VARCHAR(50)  NOT NULL COMMENT '城市',
  sign_date DATE  NOT NULL COMMENT '签约日期',
  repayment_amount DECIMAL(15,2) NOT NULL COMMENT '回款金额',
  repayment_date DATE COMMENT '回款日期',
  repayment_type VARCHAR(50) COMMENT '回款类型',
  channel_point VARCHAR(50) COMMENT '通道点位',
  channel_fee VARCHAR(50) COMMENT '通道费用',
  salesperson VARCHAR(50) COMMENT '业务员',
  remark TEXT COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_customer_name (customer_name),
  INDEX idx_repayment_date (repayment_date),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回款管理表';


-- 还款计划表
CREATE TABLE finance_repayment_plan (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  application_id BIGINT NOT NULL COMMENT '进件ID',
  customer_name VARCHAR(100) NOT NULL COMMENT '客户姓名',
  sign_date DATE COMMENT '签约日期',
  period INT DEFAULT 0 COMMENT '期数',
  total_period INT DEFAULT 0 COMMENT '总期数',
  paid_amount DECIMAL(15,2) DEFAULT 0.00 COMMENT '已还金额',
  due_amount DECIMAL(15,2) COMMENT '应还金额',
  due_date DATE COMMENT '应还日期',
  status VARCHAR(20) DEFAULT 'pending' COMMENT '状态',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_order_id (order_id),
  INDEX idx_customer_name (customer_name),
  INDEX idx_due_date (due_date),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='还款计划表';